///////////////////////////////////////////////////////////////////////////////
///
/// Copyright 2018-2020, Capvidia, Metrosage, and project contributors
/// https://www.capvidia.com/
/// 
/// This software is provided for free use to the QIF Community under the 
/// following license:
/// 
/// Boost Software License - Version 1.0 - August 17th, 2003
/// https://www.boost.org/LICENSE_1_0.txt
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;

namespace Re.Document
{
    public class Qif
    {
        // TODO create valid empty document (uuid, maxid, namespace...)

        public static Qif CreateFromFile(string fileName)
        {
            var doc = new Qif();
            doc.m_dom = new XmlDocument();
            doc.m_dom.Load(fileName);
            doc.NamespaceManager = new XmlNamespaceManager(doc.m_dom.NameTable);
            doc.NamespaceManager.AddNamespace("t", NamespaceUri);
            return doc;
        }

        public static Qif CreateRulesEmpty()
        {
            // create document
            var doc = new Qif();
            doc.m_dom = new XmlDocument();

            // initialize namespace manager
            doc.NamespaceManager = new XmlNamespaceManager(doc.m_dom.NameTable);
            doc.NamespaceManager.AddNamespace("t", NamespaceUri);

            // create root QIDDocument
            var root = doc.m_dom.CreateElement("QIFDocument", NamespaceUri);
            root.SetAttribute("versionQIF", "3.0.0");
            doc.m_dom.AppendChild(root);

            // add QPId
            var qpid = doc.m_dom.CreateElement("QPId", NamespaceUri);
            qpid.InnerText = Guid.NewGuid().ToString();
            root.AppendChild(qpid);

            // add Rules
            root.AppendChild(doc.m_dom.CreateElement("Rules", NamespaceUri));
            return doc;
        }

        public void ResetRules(Re.Rules.Qif qifRules)
        {
            // remove old rules element
            var rules = Rules;
            Rules.ParentNode.RemoveChild(rules);

            // create new rules element
            using (var xw = m_dom.DocumentElement.CreateNavigator().AppendChild())
            {
                xw.WriteWhitespace("");
                qifRules.Serialize(xw);
            }
            Debug.Assert(Rules != null);
        }

        public void Write(string fileName) => m_dom.Save(fileName);

        public bool Validate() => Validator().Validate(Root);

        public string ValidateMessages()
        {
            if (m_validator == null)
                return "";
            return Validator().ToDebugText();
        }

        public XmlNode Rules => m_dom.SelectSingleNode("t:QIFDocument/t:Rules", NamespaceManager);

        public XmlNode Root => m_dom.DocumentElement;

        private Re.XmlValidator Validator()
        {
            if (m_validator == null)
            {
                // TODO include schema to project, use relative path
                m_validator = Re.XmlValidator.Create(new string[1]
                {
                @"c:\projects\3dv_trunk\Data\qif3\QIFApplications\QIFDocument.xsd"
                });
            }
            return m_validator;
        }

        private XmlNamespaceManager NamespaceManager { get; set; }

        private const string NamespaceUri = "http://qifstandards.org/xsd/qif3";

        private XmlDocument m_dom;
        private Re.XmlValidator m_validator;

    }
}
