///////////////////////////////////////////////////////////////////////////////
///
/// Copyright 2018-2020, Capvidia and QIF Rules Editor contributors
/// https://www.capvidia.com/
/// 
/// This software is provided for free use to the QIF Community under the 
/// following license:
/// 
/// Boost Software License - Version 1.0 - August 17th, 2003
/// https://www.boost.org/LICENSE_1_0.txt
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.

using Antlr4.Runtime;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Re.Rules
{
    public class Ast
    {
        public Ast(Language language)
        {
            // create lexer
            m_lexer = new Grammar.rulesLexer(new AntlrInputStream(language.Text));
            m_lexer.RemoveErrorListeners();
            m_lexer.AddErrorListener(m_lexerErrorListener);

            // create parser
            m_parser = new Grammar.rulesParser(new CommonTokenStream(m_lexer));
            m_parser.RemoveErrorListeners();
            m_parser.AddErrorListener(m_parserErrorListener);

            // parse
            m_root = m_parser.dme_rules();
        }

        public Re.Qif3.QIFRulesType ToQifRules()
        {
            var qifRules = new Re.Qif3.QIFRulesType();
            var visitor = new AstVisitorQif();
            qifRules.DMESelectionRules = visitor.Accept(m_root);
            return qifRules;
        }

        public string ToStringTree() => m_root.ToStringTree(m_parser);

        public IEnumerable<SyntaxError> LexerErrors => m_lexerErrorListener.Errors;

        public IEnumerable<SyntaxError> ParserErrors => m_parserErrorListener.Errors;

        public bool HasError()
        {
            Debug.Assert((m_lexerErrorListener.IsEmpty && m_parserErrorListener.IsEmpty) == (m_parser.NumberOfSyntaxErrors == 0));
            return !m_lexerErrorListener.IsEmpty || !m_parserErrorListener.IsEmpty;
        }

        public string ToDebugText()
        {
            //  [Lexer error: <lexer_error>
            //  ...]
            //  [Parser error: <parser_errors>
            //  ...]
            //  AST:
            //  <AST>
            var s = new StringBuilder();
            foreach (var err in LexerErrors)
                s.AppendLine($"Lexer error: {err}");
            foreach (var err in ParserErrors)
                s.AppendLine($"Parser error: {err}");
            s.AppendLine("AST:");
            s.Append(ToStringTree());
            return s.ToString();
        }

        private Re.Grammar.rulesLexer m_lexer;
        private Re.Grammar.rulesParser m_parser;
        private Re.Grammar.rulesParser.Dme_rulesContext m_root;
        private LexerErrorListener m_lexerErrorListener = new LexerErrorListener();
        private ParserErrorListener m_parserErrorListener = new ParserErrorListener();
    }

    public class LexerErrorListener : IAntlrErrorListener<int>
    {
        public virtual void SyntaxError(IRecognizer recognizer, int offendingSymbol, int line, int charPositionInLine, string msg, RecognitionException e)
        {
            m_errors.Add(new SyntaxError(line, charPositionInLine, msg));;
        }
        public bool IsEmpty => m_errors.Count == 0;
        public IEnumerable<SyntaxError> Errors => m_errors;

        private List<SyntaxError> m_errors = new List<SyntaxError>();
    }

    public class ParserErrorListener : IAntlrErrorListener<IToken>
    {
        public virtual void SyntaxError(IRecognizer recognizer, IToken offendingSymbol, int line, int charPositionInLine, string msg, RecognitionException e)
        {
            m_errors.Add(new SyntaxError(line, charPositionInLine, msg));
        }
        public bool IsEmpty => m_errors.Count == 0;
        public IEnumerable<SyntaxError> Errors => m_errors;

        private List<SyntaxError> m_errors = new List<SyntaxError>();
    }
}
