///////////////////////////////////////////////////////////////////////////////
///
/// Copyright 2018-2020, Capvidia, Metrosage, and project contributors
/// https://www.capvidia.com/
/// 
/// This software is provided for free use to the QIF Community under the 
/// following license:
/// 
/// Boost Software License - Version 1.0 - August 17th, 2003
/// https://www.boost.org/LICENSE_1_0.txt
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.

using ICSharpCode.AvalonEdit.Highlighting;
using ICSharpCode.AvalonEdit.Highlighting.Xshd;
using Re.Rules;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Re.Wpf
{
    public class RulesEditorApp
    {
        /// <summary> Gets application instance. </summary>
        public static RulesEditorApp One { get; } = new RulesEditorApp();

        /// <summary> Gets formats which is available to open. </summary>
        public static Format[] SupportedFormatsOpen { get; } = new Format[] { Formats.Qif, Formats.Rml };

        /// <summary> Gets formats which is available to save. </summary>
        public static Format[] SupportedFormatsSave { get; } = new Format[] { Formats.Qif, Formats.Rml };

        /// <summary> Gets settings of the editor. </summary>
        public static SettingsViewModel Settings { get; } = new SettingsViewModel();

        /// <summary> Loads highlighting definition. </summary>
        /// <returns> Loaded highlighting definition </returns>
        public static IHighlightingDefinition LoadHighlightingDefinition()
        {
            string path = @"Data\RulesSyntax.xml";
            try
            {
                using (var xmlReader = System.Xml.XmlReader.Create(path))
                    return HighlightingLoader.Load(xmlReader, null);
            }
            catch (Exception e)
            {
                App.Logger.Error(e, "Failed to load highlighting definition");
                return null;
            }
        }

        /// <summary> Loads settings of the editor. </summary>
        public void LoadSettings()
        {
            if (!File.Exists(PathSettings))
                return;

            try
            {
                var xml = new XmlSerializer(typeof(SettingsViewModel));
                using (var sr = new StreamReader(PathSettings))
                    Settings.Apply(xml.Deserialize(sr) as SettingsViewModel);
            }
            catch (Exception e)
            {
                App.Logger.Error(e, "Failed to load settings");
            }
        }

        /// <summary> Loads settings of the editor. </summary>
        public void SaveSettings()
        {
            try
            {
                Directory.CreateDirectory(AppDataPath);
                var xml = new XmlSerializer(typeof(SettingsViewModel));
                using (var sw = new StreamWriter(PathSettings))
                    xml.Serialize(sw, Settings);
            }
            catch (Exception e)
            {
                App.Logger.Error(e, "Failed to save settings");
            }
        }

        /// <summary> Gets application name. </summary>
        public string Name => "Rules Editor";

        /// <summary> Gets path to application folder in %AppData%. </summary>
        public string AppDataPath => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), Name);
        private RulesEditorApp() { }
        private string PathSettings => Path.Combine(AppDataPath, "options.xml");
    }
}
