///////////////////////////////////////////////////////////////////////////////
///
/// Copyright 2018-2020, Capvidia, Metrosage, and project contributors
/// https://www.capvidia.com/
/// 
/// This software is provided for free use to the QIF Community under the 
/// following license:
/// 
/// Boost Software License - Version 1.0 - August 17th, 2003
/// https://www.boost.org/LICENSE_1_0.txt
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.

using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Re.Wpf
{
    /// <summary> Utilities. </summary>
    static class Utilities
    {
        /// <summary> Creates a string based on the specified formats which can be used for open/save file dialogs. </summary>
        /// <param name="formats"> in. Formats </param>
        public static string CreateFilter(IEnumerable<Format> formats)
        {
            var sb = new StringBuilder();

            // add filter for each format
            foreach (var f in formats)
                sb.Append(CreateFilter(f) + "|");
            //sb.Remove(sb.Length - 1, 1);

            // add All files filter
            sb.Append("All Formats|");
            foreach (var f in formats)
                sb.AppendFormat("*.{0};", f.Extension);
            sb.Remove(sb.Length - 1, 1);

            return sb.ToString();
        }

        /// <summary> Creates a string based on the specified format which can be used for open/save file dialogs. </summary>
        /// <param name="formats"> in. Format </param>
        public static string CreateFilter(Format f)
        {
            return $"{f.Description} (.{f.Extension})|*.{f.Extension}";
        }

        /// <summary> Shows a save file dialog and returns the chosen path. </summary>
        /// <param name="path"> Chosen path </param>
        /// <param name="formats"> Allowed formats </param>
        /// <param name="owner"> Owner window </param>
        /// <returns> True if used has chosen a path </returns>
        public static bool ShowSaveDialog(out string path, IReadOnlyList<Format> formats, System.Windows.Window owner)
        {
            path = string.Empty;
            var dialog = new SaveFileDialog()
            {
                Filter = CreateFilter(formats),
                FilterIndex = formats.Count + 1
            };
            if (!dialog.ShowDialog(owner).GetValueOrDefault(false))
                return false;

            path = dialog.FileName;
            return true;
        }
    }
}
